name: multi_agent_sc2_env
channels: 
  - defaults
  - conda-forge
dependencies:
  - python=3.12.0

  # Core packages
  - numpy=1.26.4
  - matplotlib=3.9.3

  # Deep learning framework
  - pytorch=2.5.1

  # Addtitional packages
  - pyyaml=6.0.2

  # GPU support
  # - cudatoolkit=11.8.0
  # - cudnn=9.3.0.75
