env:
  # SMACv2 environment configuration params
  distribution_config:
    n_units: 5
    n_enemies: 5
    team_gen:
      dist_type: weighted_teams
      unit_types: ["marine", "marauder", "medivac"]
      exception_unit_types: ["medivac"]
      weights: [1.0, 0.0, 0.0]
      observe: true
    start_positions:
      dist_type: surrounded_and_reflect
      p: 0.5
      n_enemies: 5
      map_x: 32
      map_y: 32
  map_name: "10gen_terran"
  debug: true
  conic_fov: false
  obs_own_pos: true
  use_unit_ranges: true
  min_attack_range: 2

agent:
  # VDN parameters
  learning_rate: 0.0005
  discount_factor: 0.99
  # ...

training:
  episodes: 100
  # ...

evaluation:
  episodes: 100
  # ...
  